# Remove any "org" or "app" fields if present
service: moneymind-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-5
  stage: ${opt:stage, 'dev'}

functions:
  root:
    handler: src/handler/main.main
    events:
      - http:
          path: /
          method: get
          cors: true

  # Expenses endpoints
  getExpenses:
    handler: src/handler/expenses.getExpenses
    events:
      - http:
          path: /api/expenses
          method: get
          cors: true

  getExpense:
    handler: src/handler/expenses.getExpense
    events:
      - http:
          path: /api/expenses/{id}
          method: get
          cors: true

  createExpense:
    handler: src/handler/expenses.createExpense
    events:
      - http:
          path: /api/expenses
          method: post
          cors: true

  updateExpense:
    handler: src/handler/expenses.updateExpense
    events:
      - http:
          path: /api/expenses/{id}
          method: put
          cors: true

  deleteExpense:
    handler: src/handler/expenses.deleteExpense
    events:
      - http:
          path: /api/expenses/{id}
          method: delete
          cors: true

  bulkCreateExpenses:
    handler: src/handler/expenses.bulkCreateExpenses
    events:
      - http:
          path: /api/expenses/bulk
          method: post
          cors: true

  # OPTIONS handler for CORS preflight
  options:
    handler: src/handler/options.handleOptions
    events:
      - http:
          path: /{proxy+}
          method: options
          cors: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
